[package]
name = "procvamp"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
egui_demo_lib = { version = "0.23.0", features = ["syntect"] }
egui_extras ="0.23.0"
syntect = "5.1.0"
egui_dock = "0.14"
iced = "0.13.1"
